version: "3.8"
services:
  envoy:
    image: envoyproxy/envoy:v1.33.0
    container_name: envoy_proxy
    ports:
      - "8081:8081" # HTTP (REST to gRPC)
      - "8082:8082" # HTTP (REST to gRPC)
      - "8083:8083" # HTTP (REST to gRPC)
      - "9901:9901" # Admin Panel
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./proto.pb:/etc/envoy/proto.pb
    networks:
      - taskflow-network
    # depends_on:
    #   - grpc-server
  # grpc-server:
  #   build:
  #     context: ./services/main-service # Path to your .NET project
  #     dockerfile: Dockerfile
  #   container_name: grpc_server
  #   ports:
  #     - "5001:5001" # Map host port 5001 to container port 5001
  #   networks:
  #     - taskflow-network
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://0.0.0.0:5001
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - taskflow-network
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092" # External access (host)
      - "9094:9094" # Internal access (Docker network)
      - "9093:9093" # Controller
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka-data:/tmp/kafka-logs
    networks:
      - taskflow-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    ports:
      - "8888:8888"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092 # Use internal port
      - SERVER_PORT=8888
    depends_on:
      - kafka
    networks:
      - taskflow-network
  kafka-topic-creator:
    image: confluentinc/cp-kafka:7.4.0

    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "
      echo '⏳ Waiting for Kafka to be available...' &&
      while ! kafka-topics --bootstrap-server kafka:9094 --list; do sleep 2; done &&
      echo '✅ Kafka is up!' &&
      kafka-topics --bootstrap-server kafka:9094 --create --if-not-exists --topic activities --partitions 3 --replication-factor 1 && 
      kafka-topics --bootstrap-server kafka:9094 --create --if-not-exists --topic notifications --partitions 3 --replication-factor 1
      "
    networks:
      - taskflow-network
  # cassandra:
  #   image: cassandra:5.0.4
  #   container_name: cassandra
  #   environment:
  #     - CASSANDRA_CLUSTER_NAME=my-cluster
  #     - CASSANDRA_BROADCAST_ADDRESS=auto
  #     - CASSANDRA_LISTEN_ADDRESS=auto
  #   ports:
  #     - "9042:9042"
  #   volumes:
  #     - cassandra-data:/var/lib/cassandra
  #   networks:
  #     - taskflow-network
  # cassandra-init:
  #   image: cassandra:5.0.4
  #   depends_on:
  #     - cassandra
  #   entrypoint: ["/bin/sh", "-c"]
  #   command: >
  #     "
  #     echo '⏳ Waiting for Cassandra to be available...' &&
  #     while ! cqlsh cassandra -e 'describe keyspaces'; do sleep 2; done &&
  #     echo '✅ Cassandra is up!' &&
  #     cqlsh cassandra -e \"
  #       CREATE KEYSPACE IF NOT EXISTS taskflow
  #       WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
  #     \"
  #     "
  #   networks:
  #     - taskflow-network
networks:
  taskflow-network:
    driver: bridge
volumes:
  esdata: {}
  kong-data: {}
  kafka-data: {}
  cassandra-data: {}
