syntax = "proto3";

option csharp_namespace = "TaskFlow.SprintService";

package project_service;

import "google/api/annotations.proto"; // Import Google API annotations
import "Base/base.proto";

service SprintService {
  rpc CreateSprint (CreateSprintReq) returns (CreateSprintRes) {
    option (google.api.http) = {
      post: "/api/v1/project/{project_id}/sprints"
      body: "*"
    };
  }
  rpc GetSprint (GetSprintReq) returns (SprintRes) {
    option (google.api.http) = {
      get: "/api/v1/project/{project_id}/sprints/{id}"
    };
  }
  rpc UpdateSprint (UpdateSprintReq) returns (SprintRes) {
    option (google.api.http) = {
      put: "/api/v1/project/{project_id}/sprints/{id}"
      body: "*"
    };
  }
  rpc DeleteSprint (DeleteSprintReq) returns (Empty) {
    option (google.api.http) = {
      delete: "/api/v1/sprints/{id}"
    };
  }
  rpc ListSprints (ListSprintsReq) returns (ListSprintsRes) {
    option (google.api.http) = {
      get: "/api/v1/project/{project_id}/sprints"
    };
  }
}

message SprintProgress {
  string date = 1;
  int32 planned_total = 2;
  int32 completed_count = 3;
  int32 remaining_count = 4;
  int32 completed_story_points = 5;
  int32 remaining_story_points = 6;
}

message SprintStatistics {
  int32 total_issues = 1;
  int32 completed_issues = 2;
  int32 total_story_points = 3;
  int32 completed_story_points = 4;
  map<string, int32> issues_by_type = 5;
  map<string, int32> issues_by_status = 6;
  repeated SprintProgress daily_progress = 7;
}

message CreateSprintReq {
  string name = 1;
  string date_started = 2;
  string date_ended = 3;
  int32 duration = 4;
  string goal = 5;
  string project_id = 6;
}

message GetSprintReq {
  string id = 1;
  string project_id = 2;
}

message UpdateSprintReq {
  string id = 1;
  string name = 2;
  string date_started = 3;
  string date_ended = 4;
  int32 duration = 5;
  string goal = 6;
  string project_id = 7;
}

message DeleteSprintReq {
  string id = 1;
  string project_id = 2;
}

message ListSprintsReq {
  string project_id = 1;
  int32 page = 2;
  int32 limit = 3;
}

message SprintRes {
  string id = 1;
  string name = 2;
  string date_started = 3;
  string date_ended = 4;
  int32 duration = 5;
  string goal = 6;
  string created_at = 7;
  string updated_at = 8;
  string project_id = 9;
  SprintStatistics statistics = 10;
}

message CreateSprintRes {
  SprintRes data = 1;
  optional base.PaginationRes pagination = 2;
}

message ListSprintsRes {
  repeated SprintRes data = 1;
  base.PaginationRes pagination = 2;
}

message Empty {}