syntax = "proto3";

option go_package = "github.com/vudinhan2525/TaskFlow-Server/services/go-service/types/main_service;main_service";
option csharp_namespace = "TaskFlow.SprintService";

package project_service;


import "google/api/annotations.proto"; // Import Google API annotations
import "base.proto";

service SprintService {
  rpc CreateSprint (CreateSprintReq) returns (CreateSprintRes) {
    option (google.api.http) = {
      post: "/api/v1/sprint/project/{project_id}"
      body: "*"
    };
  }
  rpc GetSprint (GetSprintReq) returns (SprintRes) {
    option (google.api.http) = {
      get: "/api/v1/sprint/project/{project_id}/{id}"
    };
  }
  rpc UpdateSprint (UpdateSprintReq) returns (SprintRes) {
    option (google.api.http) = {
      put: "/api/v1/sprint/project/{project_id}/{id}"
      body: "*"
    };
  }
  rpc DeleteSprint (DeleteSprintReq) returns (Empty) {
    option (google.api.http) = {
      delete: "/api/v1/sprint/{id}"
    };
  }
  rpc ListSprints (ListSprintsReq) returns (ListSprintsRes) {
    option (google.api.http) = {
      post: "/api/v1/sprints/list-sprints",
      body: "*"
    };
  }
  rpc GetSprintStats (GetSrintStatsReq) returns (GetSrintStatsRes) {
    option (google.api.http) = {
      get: "/api/v1/sprint/project/{project_id}/{sprint_id}/stats"
    };
  }
}

message GetSrintStatsReq {
  string sprint_id = 1;
}

message GetSrintStatsRes {
  string status = 1;
  string message = 2;
  SprintStatData data = 3;
}
message SprintStatData {
  SprintRes sprint = 1;
  SprintStats sprint_stats = 2;
  repeated SprintDailyStats sprint_daily_stats = 3;
}
message SprintStats {
  int32 total_issues = 1;
  int32 completed_issues = 2;
  int32 total_story_point = 3;
  int32 completed_story_point = 4;
}
message SprintDailyStats {
  string date = 1;
  int32 completed_issues = 2;
  int32 remaining_issues = 3;
}

// Sprint Messages
message CreateSprintReq {
  string name = 1;
  string date_started = 2;
  string date_ended = 3;
  int32 duration = 4;
  string goal = 5;
  string project_id = 6;
}

message GetSprintReq {
  string id = 1;
  string project_id = 2;
}

message UpdateSprintReq {
  string id = 1;
  string name = 2;
  string date_started = 3;
  string date_ended = 4;
  int32 duration = 5;
  string goal = 6;
  string project_id = 7;
}

message DeleteSprintReq {
  string id = 1;
  string project_id = 2;
}

message ListSprintsReq {
  optional string project_id = 1;
  repeated string sprint_ids = 2;
  int32 page = 3;
  int32 limit = 4;
}

message SprintRes {
  string id = 1;
  string name = 2;
  string date_started = 3;
  string date_ended = 4;
  int32 duration = 5;
  string goal = 6;
  string created_at = 7;
  string updated_at = 8;
  string project_id = 9;
}

message CreateSprintRes {
  SprintRes data = 1;
  optional base.PaginationRes pagination = 2;
}

message ListSprintsRes {
  repeated SprintRes data = 1;
  base.PaginationRes pagination = 2;
}

message Empty {}