syntax = "proto3";

option go_package = "github.com/vudinhan2525/TaskFlow-Server/services/go-service/types/main_service;main_service";
option csharp_namespace = "TaskFlow.UserService";

package project_service;
import "base.proto";
import "google/api/annotations.proto";

// Define the gRPC service
service UserService {
  rpc CreateUser (CreateUserReq) returns (CreateUserRes) {
    option (google.api.http) = {
      post: "/api/v1/users"
      body: "*"
    };
  }
  rpc Login (LoginUserReq) returns (LoginUserRes) {
    option (google.api.http) = {
      post: "/api/v1/users/login"
      body: "*"
    };
  }
  rpc Register (RegisterUserReq) returns (RegisterUserRes) {  
    option (google.api.http) = {
      post: "/api/v1/users/register"
      body: "*"
    };
  }
  rpc VerifyOTP (VerifyOTPReq) returns (VerifyOTPRes) {
    option (google.api.http) = {
      post: "/api/v1/users/verify"
      body: "*"
    };
  }
  rpc ResendOTP (ResendOTPReq) returns (ResendOTPRes) {
    option (google.api.http) = {
      post: "/api/v1/users/resend-otp"
      body: "*"
    };
  }
  rpc UpdateUser (UpdateUserReq) returns (UpdateUserRes) {
    option (google.api.http) = {
      put: "/api/v1/users"
      body: "*"
    };
  }
  rpc GetById (GetUserReq) returns (GetUserRes) {
    option (google.api.http) = {
      get: "/api/v1/users/{user_id}"
    };
  }
  rpc GetMe (GetUserReq) returns (GetUserRes) {
    option (google.api.http) = {
      get: "/api/v1/users/get-me"
    };
  }

  rpc GetByEmail (GetUserByEmailReq) returns (GetUserRes) {
    option (google.api.http) = {
      get: "/api/v1/users/by-email/{email}"
    };
  }
  rpc ListUsers(ListUsersReq) returns (ListUsersRes){
    option (google.api.http) = {
      get: "/api/v1/users/list-users"
    };
  }
  rpc Logout (LogoutUserReq) returns (LogoutUserRes) {
    option (google.api.http) = {
      post: "/api/v1/users/logout"
      body: "*"
    };
  }
  rpc GetStats (GetStatsReq) returns (GetStatsRes) {
    option (google.api.http) = {
      post: "/api/v1/users/stats"
      body: "*"
    };
  }
  rpc ChangePassword (ChangePasswordReq) returns (ChangePasswordRes) {
    option (google.api.http) = {
      post: "/api/v1/users/change-password"
      body: "*"
    };
  }
}

message ChangePasswordReq {
  string user_id = 1;
  string old_password = 2;
  string new_password = 3;
}

message ChangePasswordRes {
  string status = 1;
  string message = 2;
}

message GetStatsReq {
  string id = 1;
  bool is_sprintId = 2;
}
message StatusCount {
  string name = 1;
  int32 count = 2;
}

message PriorityCount {
  string priority = 1;
  int32 count = 2;
}

message TypeCount {
  string type = 1;
  int32 count = 2;
}

message UserStats {
  repeated StatusCount by_status = 1;
  repeated PriorityCount by_priority = 2;
  repeated TypeCount by_type = 3;
  int32 new_issues_count = 4;
  int32 recently_updated_count = 5;
}

message GetStatsRes {
  string status = 1;
  string message = 2;
  UserStats data = 3; 
}

// LogoutUserReq and LogoutUserRes
message LogoutUserReq {
}

message LogoutUserRes {
  string status = 1;
  string message = 2;
}

// LOGIN
message LoginUserReq {
  string email = 1;
  string password = 2;
}

message LoginUserRes {
  string status = 1;
  string message = 2;
  base.UserRes data = 3;
}

// Get user by email
message GetUserByEmailReq {
  string email = 1;
}

// Get one user
message GetUserReq {
  string user_id = 1;
}

message GetUserRes {
  string status = 1;
  base.UserRes data = 2;
}
// List User
message ListUsersReq {
  optional string name = 1;
  optional string email = 2;
  optional string project_id = 3;
  repeated string user_ids = 4;
  int32 page = 5;
  int32 limit = 6;
}

message ListUsersRes{
  string status = 1;
  repeated base.UserRes data = 2;
  base.PaginationRes pagination = 3;
}

// Update User
message UpdateUserReq {
  optional string first_name = 1;
  optional string last_name = 2;
  optional string email = 3;
  optional string password = 4;
  optional string role = 5;
  optional string avatar = 6;
}

message UpdateUserRes {
  string status = 1;
  base.UserRes data = 2;
}

// Create User
message CreateUserReq {
  string first_name = 1;
  string last_name = 2;
  string email = 3;
  string password = 4;
  string role = 5;
}

message CreateUserRes {
  string status = 1;
  base.UserRes data = 2;
}

// Register User
message RegisterUserReq {
  string first_name = 1;
  string last_name = 2;
  string email = 3;
  string password = 4;
  string password_confirm = 5;
}
message RegisterUserRes {
  string status = 1;
  string message = 2;
}

// Verify OTP User
message VerifyOTPReq {
  string email = 1;
  string otp = 2;
}
message VerifyOTPRes {
  string status = 1;
  string message = 2;
  base.UserRes data = 3;
}

// Resend OTP User
message ResendOTPReq {
  string email = 1;
}
message ResendOTPRes {
  string status = 1;
  string message = 2;
}